version: "3.5"
services:
     bbs:
      build:
        context: . 
        dockerfile: Dockerfile
      ports:
        - "403:403"
      command: sh -c './wait-for db:3306 -- ./bbs'
      volumes:
        - type: volume
          source: counter-vol
          target: /go/src/bbs
     db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - "3307:3306"
      environment:
        MYSQL_ROOT_PASSWORD: soojin206
        MYSQL_DATABASE: bbs_test
volumes:
  counter-vol:
     
