version: "3.5"
services:
     bbs:
      build:
        context: . 
        dockerfile: Dockerfile
      ports:
        - "403:403"
      depends_on:
       - db
      links:
        - db
      networks: 
        - bbsserver
      volumes:
        - type: volume
          source: counter-vol
          target: /go/src/bbs
     db:
      image: mysql:latest
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      ports:
        - "3306:3307"
      networks: 
        - bbsserver
      environment:
        MYSQL_ROOT_PASSWORD: soojin206
        MYSQL_DATABASE: bbs_test
        
networks:
  bbsserver:
    driver: "bridge"

volumes:
  counter-vol:
     
